### ISSUE TITLE
Fail  to install

### ISSUE THREAD

**Issue by gmhafiz** [PadreIDE/Parse-ErrorString-Perl#2]
Package Version: Parse-ErrorString-Perl-0.19
Perl version: 5.22.0
OS: Manjaro Linux 4.1.13-1 x86_64 GNU/Linux

Installing through cpan with install Parse::ErrorString::Perl gives the following error:
Running install for module 'Parse::ErrorString::Perl'
Checksum for /home/$USER/.cpan/sources/authors/id/S/SZ/SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring S/SZ/SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Parse::ErrorString::Perl
Writing MYMETA.yml and MYMETA.json
  SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for S/SZ/SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz
cp lib/Parse/ErrorString/Perl/StackItem.pm blib/lib/Parse/ErrorString/Perl/StackItem.pm
cp lib/Parse/ErrorString/Perl/ErrorItem.pm blib/lib/Parse/ErrorString/Perl/ErrorItem.pm
cp lib/Parse/ErrorString/Perl.pm blib/lib/Parse/ErrorString/Perl.pm
cp bin/check_perldiag blib/script/check_perldiag
"/usr/bin/perl" "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/check_perldiag
Manifying 1 pod document
Manifying 3 pod documents
  SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/_.t
t/01-errors.t ............. ok  
t/02-diagnostics.t ........ ok  
t/03-split_diagnostics.t .. ok  
t/04-perldiag.t ........... 1/4 Use of uninitialized value $obtained_diagnostics in substitution (s///) at t/04-perldiag.t line 63.
# Failed test 'diagnostics'
# at t/04-perldiag.t line 64.
# +---+-------+---+-----------------------------------------------------------------------------+
# | Ln|Got    | Ln|Expected                                                                     |
# +---+-------+---+-----------------------------------------------------------------------------+
# \*  1|undef  \*  1|'(F) You\'ve said "use strict" or "use strict vars", which indicates\n       *
# |   |       \*  2|that all variables must either be lexically scoped (using "my" or "state"),  *
# |   |       \*  3|declared beforehand using "our", or explicitly qualified to say              *
# |   |       \*  4|which package the global variable is in (using "::").'                       *
# +---+-------+---+-----------------------------------------------------------------------------+
# Failed test 'type'
# at t/04-perldiag.t line 65.
# got: undef
# expected: 'F'
# Failed test 'error type'
# at t/04-perldiag.t line 66.
# got: undef
# expected: 'fatal error'
# Looks like you failed 3 tests of 4.

t/04-perldiag.t ........... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/4 subtests 
t/05-stacktrace.t ......... ok  
t/06-short_filename.t ..... ok  
t/10-check_perldiag.t ..... ok   
## Test Summary Report

t/04-perldiag.t         (Wstat: 768 Tests: 4 Failed: 3)
  Failed tests:  2-4
  Non-zero exit status: 3
Files=7, Tests=90,  2 wallclock secs ( 0.04 usr  0.00 sys +  2.14 cusr  0.04 csys =  2.22 CPU)
Result: FAIL
Failed 1/7 test programs. 3/90 subtests failed.
Makefile:807: recipe for target 'test_dynamic' failed
make: **\* [test_dynamic] Error 255
  SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz
Failed during this command:
 SZABGAB/Parse-ErrorString-Perl-0.21.tar.gz   : make_test NO

**Comment by szabgab** [comment]
Version 0.22 should fix this. Please try again with that version. See also #1
